//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: vme.proto
namespace OpenMMDFormat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"vec2")]
  public partial class vec2 : global::ProtoBuf.IExtensible
  {
    public vec2() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bvec2")]
  public partial class bvec2 : global::ProtoBuf.IExtensible
  {
    public bvec2() {}
    
    private uint _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }
    private uint _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"vec3")]
  public partial class vec3 : global::ProtoBuf.IExtensible
  {
    public vec3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"vec4")]
  public partial class vec4 : global::ProtoBuf.IExtensible
  {
    public vec4() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _w;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Header")]
  public partial class Header : global::ProtoBuf.IExtensible
  {
    public Header() {}
    
    private string _versionInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"versionInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string versionInfo
    {
      get { return _versionInfo; }
      set { _versionInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _modelInfo = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"modelInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> modelInfo
    {
      get { return _modelInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IDTag")]
  public partial class IDTag : global::ProtoBuf.IExtensible
  {
    public IDTag() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BezInterpolParams")]
  public partial class BezInterpolParams : global::ProtoBuf.IExtensible
  {
    public BezInterpolParams() {}
    
    private OpenMMDFormat.bvec2 _X1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"X1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 X1
    {
      get { return _X1; }
      set { _X1 = value; }
    }
    private OpenMMDFormat.bvec2 _X2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"X2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 X2
    {
      get { return _X2; }
      set { _X2 = value; }
    }
    private OpenMMDFormat.bvec2 _Y1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Y1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 Y1
    {
      get { return _Y1; }
      set { _Y1 = value; }
    }
    private OpenMMDFormat.bvec2 _Y2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Y2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 Y2
    {
      get { return _Y2; }
      set { _Y2 = value; }
    }
    private OpenMMDFormat.bvec2 _Z1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Z1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 Z1
    {
      get { return _Z1; }
      set { _Z1 = value; }
    }
    private OpenMMDFormat.bvec2 _Z2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Z2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 Z2
    {
      get { return _Z2; }
      set { _Z2 = value; }
    }
    private OpenMMDFormat.bvec2 _R1;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"R1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 R1
    {
      get { return _R1; }
      set { _R1 = value; }
    }
    private OpenMMDFormat.bvec2 _R2;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"R2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 R2
    {
      get { return _R2; }
      set { _R2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CameraExtraBezParams")]
  public partial class CameraExtraBezParams : global::ProtoBuf.IExtensible
  {
    public CameraExtraBezParams() {}
    
    private OpenMMDFormat.bvec2 _L1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"L1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 L1
    {
      get { return _L1; }
      set { _L1 = value; }
    }
    private OpenMMDFormat.bvec2 _L2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"L2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 L2
    {
      get { return _L2; }
      set { _L2 = value; }
    }
    private OpenMMDFormat.bvec2 _V1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"V1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 V1
    {
      get { return _V1; }
      set { _V1 = value; }
    }
    private OpenMMDFormat.bvec2 _V2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"V2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.bvec2 V2
    {
      get { return _V2; }
      set { _V2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BoneFrame")]
  public partial class BoneFrame : global::ProtoBuf.IExtensible
  {
    public BoneFrame() {}
    
    private ulong _frameNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong frameNumber
    {
      get { return _frameNumber; }
      set { _frameNumber = value; }
    }
    private OpenMMDFormat.vec3 _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.vec3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private OpenMMDFormat.vec4 _rotation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.vec4 rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private OpenMMDFormat.BezInterpolParams _interpolParameters = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"interpolParameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OpenMMDFormat.BezInterpolParams interpolParameters
    {
      get { return _interpolParameters; }
      set { _interpolParameters = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MorphFrame")]
  public partial class MorphFrame : global::ProtoBuf.IExtensible
  {
    public MorphFrame() {}
    
    private ulong _frameNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong frameNumber
    {
      get { return _frameNumber; }
      set { _frameNumber = value; }
    }
    private float _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CameraFrame")]
  public partial class CameraFrame : global::ProtoBuf.IExtensible
  {
    public CameraFrame() {}
    
    private ulong _frameNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong frameNumber
    {
      get { return _frameNumber; }
      set { _frameNumber = value; }
    }
    private OpenMMDFormat.vec3 _position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.vec3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private OpenMMDFormat.vec3 _rotation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.vec3 rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private float _distance;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private OpenMMDFormat.BezInterpolParams _interpolParameters = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"interpolParameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OpenMMDFormat.BezInterpolParams interpolParameters
    {
      get { return _interpolParameters; }
      set { _interpolParameters = value; }
    }
    private OpenMMDFormat.CameraExtraBezParams _cameraInterpolParams = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"cameraInterpolParams", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OpenMMDFormat.CameraExtraBezParams cameraInterpolParams
    {
      get { return _cameraInterpolParams; }
      set { _cameraInterpolParams = value; }
    }
    private ulong _viewAngle;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"viewAngle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong viewAngle
    {
      get { return _viewAngle; }
      set { _viewAngle = value; }
    }
    private uint _perspective;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"perspective", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint perspective
    {
      get { return _perspective; }
      set { _perspective = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LightFrame")]
  public partial class LightFrame : global::ProtoBuf.IExtensible
  {
    public LightFrame() {}
    
    private ulong _frameNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong frameNumber
    {
      get { return _frameNumber; }
      set { _frameNumber = value; }
    }
    private OpenMMDFormat.vec3 _color;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.vec3 color
    {
      get { return _color; }
      set { _color = value; }
    }
    private OpenMMDFormat.vec3 _position;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.vec3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelfShadowFrame")]
  public partial class SelfShadowFrame : global::ProtoBuf.IExtensible
  {
    public SelfShadowFrame() {}
    
    private ulong _frameNumber;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong frameNumber
    {
      get { return _frameNumber; }
      set { _frameNumber = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private float _distance;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IKInfo")]
  public partial class IKInfo : global::ProtoBuf.IExtensible
  {
    public IKInfo() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _isOn;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isOn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint isOn
    {
      get { return _isOn; }
      set { _isOn = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShowIKFrame")]
  public partial class ShowIKFrame : global::ProtoBuf.IExtensible
  {
    public ShowIKFrame() {}
    
    private ulong _frame;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong frame
    {
      get { return _frame; }
      set { _frame = value; }
    }
    private uint _show;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"show", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint show
    {
      get { return _show; }
      set { _show = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.IKInfo> _ikInfo = new global::System.Collections.Generic.List<OpenMMDFormat.IKInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ikInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.IKInfo> ikInfo
    {
      get { return _ikInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BoneFrameTable")]
  public partial class BoneFrameTable : global::ProtoBuf.IExtensible
  {
    public BoneFrameTable() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.BoneFrame> _frames = new global::System.Collections.Generic.List<OpenMMDFormat.BoneFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.BoneFrame> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MorphFrameTable")]
  public partial class MorphFrameTable : global::ProtoBuf.IExtensible
  {
    public MorphFrameTable() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.MorphFrame> _frames = new global::System.Collections.Generic.List<OpenMMDFormat.MorphFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.MorphFrame> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CameraFrameTable")]
  public partial class CameraFrameTable : global::ProtoBuf.IExtensible
  {
    public CameraFrameTable() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.CameraFrame> _frames = new global::System.Collections.Generic.List<OpenMMDFormat.CameraFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.CameraFrame> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LightFrameTable")]
  public partial class LightFrameTable : global::ProtoBuf.IExtensible
  {
    public LightFrameTable() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.LightFrame> _frames = new global::System.Collections.Generic.List<OpenMMDFormat.LightFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.LightFrame> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelfShadowFrameTable")]
  public partial class SelfShadowFrameTable : global::ProtoBuf.IExtensible
  {
    public SelfShadowFrameTable() {}
    
    private ulong _id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.SelfShadowFrame> _frames = new global::System.Collections.Generic.List<OpenMMDFormat.SelfShadowFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.SelfShadowFrame> frames
    {
      get { return _frames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VocaloidMotionEvolved")]
  public partial class VocaloidMotionEvolved : global::ProtoBuf.IExtensible
  {
    public VocaloidMotionEvolved() {}
    
    private OpenMMDFormat.Header _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public OpenMMDFormat.Header header
    {
      get { return _header; }
      set { _header = value; }
    }
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.IDTag> _boneIDTable = new global::System.Collections.Generic.List<OpenMMDFormat.IDTag>();
    [global::ProtoBuf.ProtoMember(2, Name=@"boneIDTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.IDTag> boneIDTable
    {
      get { return _boneIDTable; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.IDTag> _morphIDTable = new global::System.Collections.Generic.List<OpenMMDFormat.IDTag>();
    [global::ProtoBuf.ProtoMember(3, Name=@"morphIDTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.IDTag> morphIDTable
    {
      get { return _morphIDTable; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.IDTag> _cameraIDTable = new global::System.Collections.Generic.List<OpenMMDFormat.IDTag>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cameraIDTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.IDTag> cameraIDTable
    {
      get { return _cameraIDTable; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.IDTag> _lightIDTable = new global::System.Collections.Generic.List<OpenMMDFormat.IDTag>();
    [global::ProtoBuf.ProtoMember(5, Name=@"lightIDTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.IDTag> lightIDTable
    {
      get { return _lightIDTable; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.IDTag> _selfShadowIDTable = new global::System.Collections.Generic.List<OpenMMDFormat.IDTag>();
    [global::ProtoBuf.ProtoMember(6, Name=@"selfShadowIDTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.IDTag> selfShadowIDTable
    {
      get { return _selfShadowIDTable; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.BoneFrameTable> _boneFrameTables = new global::System.Collections.Generic.List<OpenMMDFormat.BoneFrameTable>();
    [global::ProtoBuf.ProtoMember(7, Name=@"boneFrameTables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.BoneFrameTable> boneFrameTables
    {
      get { return _boneFrameTables; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.MorphFrameTable> _morphFrameTables = new global::System.Collections.Generic.List<OpenMMDFormat.MorphFrameTable>();
    [global::ProtoBuf.ProtoMember(8, Name=@"morphFrameTables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.MorphFrameTable> morphFrameTables
    {
      get { return _morphFrameTables; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.CameraFrameTable> _cameraFrameTables = new global::System.Collections.Generic.List<OpenMMDFormat.CameraFrameTable>();
    [global::ProtoBuf.ProtoMember(9, Name=@"cameraFrameTables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.CameraFrameTable> cameraFrameTables
    {
      get { return _cameraFrameTables; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.LightFrameTable> _lightFrameTables = new global::System.Collections.Generic.List<OpenMMDFormat.LightFrameTable>();
    [global::ProtoBuf.ProtoMember(10, Name=@"lightFrameTables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.LightFrameTable> lightFrameTables
    {
      get { return _lightFrameTables; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.SelfShadowFrameTable> _selfShadowFrameTables = new global::System.Collections.Generic.List<OpenMMDFormat.SelfShadowFrameTable>();
    [global::ProtoBuf.ProtoMember(11, Name=@"selfShadowFrameTables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.SelfShadowFrameTable> selfShadowFrameTables
    {
      get { return _selfShadowFrameTables; }
    }
  
    private readonly global::System.Collections.Generic.List<OpenMMDFormat.ShowIKFrame> _showIKFrames = new global::System.Collections.Generic.List<OpenMMDFormat.ShowIKFrame>();
    [global::ProtoBuf.ProtoMember(12, Name=@"showIKFrames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpenMMDFormat.ShowIKFrame> showIKFrames
    {
      get { return _showIKFrames; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}